In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.23.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas) (1.14.0)
WARNING: You are using pip version 20.2.4; however, version 23.0.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

In [1]:
import os
import pandas as pd
import numpy as np
#import networkx as nx
#import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [3]:
hidden_units = [32, 32]
learning_rate = 0.01
dropout_rate = 0.5
num_epochs = 2
batch_size = 8 #256

In [4]:
def compile_model(model):
    # Compile the model.
    model.compile(
        optimizer="rmsprop",
        #optimizer=keras.optimizers.Adam(learning_rate),
        loss="binary_crossentropy",
        # Tati: categorical_crossentropy, expects the labels to follow a categorical encoding. 
        #       With integer labels, you should use sparse_categorical_crossentropy.
        #       This new loss function is still mathematically the same as categorical_crossentropy; it just has a different interface.
        #metrics=[keras.metrics.SparseCategoricalAccuracy(name="acc")],
    )
    # Create an early stopping callback.
    #early_stopping = keras.callbacks.EarlyStopping(
    #    monitor="val_acc", patience=50, restore_best_weights=True
    #
    #)
    return model

# This function trains an input model using the given training data.
def run_experiment(model, x_train, y_train): 
    guardarModelo = keras.callbacks.ModelCheckpoint(
        #filepath="/mnt/modelos1/",  # "checkpoint_path.keras",
        filepath="/mnt/modelos_iscx/",
        monitor="val_loss",
        save_best_only=True,
        save_format="tf",
    )
    # Fit the model.
    history = model.fit(
        x=x_train,
        y=y_train,
        epochs=num_epochs,
        batch_size=batch_size,
        validation_split=0.15,
        callbacks=[guardarModelo], #early_stopping],
    )

    return history


def create_ffn(hidden_units, dropout_rate, name=None):
    fnn_layers = []

    for units in hidden_units:
        fnn_layers.append(layers.BatchNormalization())
        fnn_layers.append(layers.Dropout(dropout_rate))
        fnn_layers.append(layers.Dense(units, activation=tf.nn.gelu))

    return keras.Sequential(fnn_layers, name=name)

In [5]:
class GraphConvLayer(layers.Layer):
    def __init__(
        self,
        hidden_units,
        dropout_rate=0.2,
        aggregation_type="mean",
        combination_type="concat",
        normalize=False,
        *args,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)

        self.aggregation_type = aggregation_type
        self.combination_type = combination_type
        self.normalize = normalize

        self.ffn_prepare = create_ffn(hidden_units, dropout_rate)
        if self.combination_type == "gated":
            self.update_fn = layers.GRU(
                units=hidden_units,
                activation="tanh",
                recurrent_activation="sigmoid",
                dropout=dropout_rate,
                return_state=True,
                recurrent_dropout=dropout_rate,
            )
        else:
            self.update_fn = create_ffn(hidden_units, dropout_rate)

    def prepare(self, node_repesentations, weights=None):
        # node_repesentations shape is [num_edges, embedding_dim].
        messages = self.ffn_prepare(node_repesentations)
        if weights is not None:
            messages = messages * tf.expand_dims(weights, -1)
        return messages

    def aggregate(self, node_indices, neighbour_messages, node_repesentations):
        # node_indices shape is [num_edges].
        # neighbour_messages shape: [num_edges, representation_dim].
        # node_repesentations shape is [num_nodes, representation_dim]
        num_nodes = node_repesentations.shape[0]
        if self.aggregation_type == "sum":
            aggregated_message = tf.math.unsorted_segment_sum(
                neighbour_messages, node_indices, num_segments=num_nodes
            )
        elif self.aggregation_type == "mean":
            aggregated_message = tf.math.unsorted_segment_mean(
                neighbour_messages, node_indices, num_segments=num_nodes
            )
        elif self.aggregation_type == "max":
            aggregated_message = tf.math.unsorted_segment_max(
                neighbour_messages, node_indices, num_segments=num_nodes
            )
        else:
            raise ValueError(f"Invalid aggregation type: {self.aggregation_type}.")

        return aggregated_message

    def update(self, node_repesentations, aggregated_messages):
        # node_repesentations shape is [num_nodes, representation_dim].
        # aggregated_messages shape is [num_nodes, representation_dim].
        if self.combination_type == "gru":
            # Create a sequence of two elements for the GRU layer.
            h = tf.stack([node_repesentations, aggregated_messages], axis=1)
        elif self.combination_type == "concat":
            # Concatenate the node_repesentations and aggregated_messages.
            h = tf.concat([node_repesentations, aggregated_messages], axis=1)
        elif self.combination_type == "add":
            # Add node_repesentations and aggregated_messages.
            h = node_repesentations + aggregated_messages
        else:
            raise ValueError(f"Invalid combination type: {self.combination_type}.")

        # Apply the processing function.
        node_embeddings = self.update_fn(h)
        if self.combination_type == "gru":
            node_embeddings = tf.unstack(node_embeddings, axis=1)[-1]

        if self.normalize:
            node_embeddings = tf.nn.l2_normalize(node_embeddings, axis=-1)
        return node_embeddings

    def call(self, inputs):
        """Process the inputs to produce the node_embeddings.

        inputs: a tuple of three elements: node_repesentations, edges, edge_weights.
        Returns: node_embeddings of shape [num_nodes, representation_dim].
        """

        node_repesentations, edges, edge_weights = inputs
        # Get node_indices (source) and neighbour_indices (target) from edges.
        node_indices, neighbour_indices = edges[0], edges[1]
        # neighbour_repesentations shape is [num_edges, representation_dim].
        neighbour_repesentations = tf.gather(node_repesentations, neighbour_indices)

        # Prepare the messages of the neighbours.
        neighbour_messages = self.prepare(neighbour_repesentations, edge_weights)
        # Aggregate the neighbour messages.
        aggregated_messages = self.aggregate(
            node_indices, neighbour_messages, node_repesentations
        )
        # Update the node embedding with the neighbour messages.
        return self.update(node_repesentations, aggregated_messages)

In [6]:
class GNNNodeClassifier(tf.keras.Model):
    def __init__(
        self,
        graph_info,
        num_classes,
        hidden_units,
        aggregation_type="sum",
        combination_type="concat",
        dropout_rate=0.2,
        normalize=True,
        *args,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)

        # Unpack graph_info to three elements: node_features, edges, and edge_weight.
        node_features, edges, edge_weights = graph_info
        self.node_features = node_features
        self.edges = edges
        self.edge_weights = edge_weights
        # Set edge_weights to ones if not provided.
        if self.edge_weights is None:
            self.edge_weights = tf.ones(shape=edges.shape[1])
        # Scale edge_weights to sum to 1.
        self.edge_weights = self.edge_weights / tf.math.reduce_sum(self.edge_weights)

        # Create a process layer.
        self.preprocess = create_ffn(hidden_units, dropout_rate, name="preprocess")
        # Create the first GraphConv layer.
        self.conv1 = GraphConvLayer(
            hidden_units,
            dropout_rate,
            aggregation_type,
            combination_type,
            normalize,
            name="graph_conv1",
        )
        # Create the second GraphConv layer.
        self.conv2 = GraphConvLayer(
            hidden_units,
            dropout_rate,
            aggregation_type,
            combination_type,
            normalize,
            name="graph_conv2",
        )
        # Create a postprocess layer.
        self.postprocess = create_ffn(hidden_units, dropout_rate, name="postprocess")
        # Create a compute logits layer.
        self.compute_logits = layers.Dense(units=num_classes, name="logits")  
          # Tati: For Tensorflow: logits is a name that it is thought to imply that this Tensor is the quantity that is being mapped to probabilities by the Softmax

    def call(self, input_node_indices):
        # Preprocess the node_features to produce node representations.
        x = self.preprocess(self.node_features)
        # Apply the first graph conv layer.
        x1 = self.conv1((x, self.edges, self.edge_weights))
        # Skip connection.
        x = x1 + x
        # Apply the second graph conv layer.
        x2 = self.conv2((x, self.edges, self.edge_weights))
        # Skip connection.
        x = x2 + x
        # Postprocess node embedding.
        x = self.postprocess(x)
        # Fetch node embeddings for the input node_indices.
        node_embeddings = tf.gather(x, input_node_indices)
        # Compute logits
        return self.compute_logits(node_embeddings)

In [7]:
# Training
training_grafos = pd.read_csv(
    "/mnt/training_GRAFOS.pkts.ncol",
    sep=" ",  
    header=None,  # no heading row
    names=["source", "target", "weight"],  # set our own names for the columns
)

training_features_tmp = pd.read_csv(
    "/mnt/training_FEATURES.pkts.SINnorm.csv",
    sep=",",  
    header=0
)


# Validation
validation_grafos = pd.read_csv(
    "/mnt/validation_GRAFOS.pkts.ncol",
    sep=" ",  
    header=None,  # no heading row
    names=["source", "target", "weight"],  # set our own names for the columns
)

validation_features_tmp = pd.read_csv(
    "/mnt/validation_FEATURES.pkts.SINnorm.csv",
    sep=",",  
    header=0
)



class_values = sorted(training_features_tmp["label"].unique())
class_idx = {name: id for id, name in enumerate(class_values)}
node_idx_train = {name: idx for idx, name in enumerate(sorted(training_features_tmp["node"].unique()))}
node_idx_val = {name: idx for idx, name in enumerate(sorted(validation_features_tmp["node"].unique()))}

training_grafos["source"] = training_grafos["source"].apply(lambda name: node_idx_train[name])
training_grafos["target"] = training_grafos["target"].apply(lambda name: node_idx_train[name])

training_features = training_features_tmp.loc[:,["node","ID","OD","IDW","ODW","label"]].copy()
training_features["node"] = training_features_tmp["node"].apply(lambda name: node_idx_train[name])
training_features["label"] = training_features_tmp["label"].apply(lambda value: class_idx[value])

validation_grafos["source"] = validation_grafos["source"].apply(lambda name: node_idx_val[name])
validation_grafos["target"] = validation_grafos["target"].apply(lambda name: node_idx_val[name])

validation_features = validation_features_tmp.loc[:,["node","ID","OD","IDW","ODW","label"]].copy()
validation_features["node"] = validation_features_tmp["node"].apply(lambda name: node_idx_val[name])
validation_features["label"] = validation_features_tmp["label"].apply(lambda value: class_idx[value])


# Create an edges array (adjacency matrix) of shape [2, num_edges]
training_edges = training_grafos[["source", "target"]].to_numpy().T
validation_edges = validation_grafos[["source", "target"]].to_numpy().T

# Create an edge weights array.
training_edge_weights = training_grafos[["weight"]].to_numpy().T 
training_edge_weights = training_edge_weights.reshape((training_edges.shape[-1],))
training_edge_weights = tf.convert_to_tensor(training_edge_weights)

# Create a node features array of shape [num_nodes, num_features].
feature_names = set(training_features.columns) - {"node", "label"}
training_node_features = tf.cast(
    training_features.sort_values("node")[feature_names].to_numpy(), dtype=tf.dtypes.float32
)

# Create graph info tuple with node_features, edges, and edge_weights.
graph_info = (training_node_features, training_edges, training_edge_weights)

print("Edges shape:", training_edges.shape)
print("Nodes shape:", training_node_features.shape)

<ipython-input-7-d4b50cdc2e0e>:64: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  training_features.sort_values("node")[feature_names].to_numpy(), dtype=tf.dtypes.float32

Edges shape: (2, 5020771)
Nodes shape: (2398933, 4)

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices((images, labels))

In [8]:
## GNN
gnn_model = GNNNodeClassifier(
    graph_info=graph_info,
    num_classes=2,
    hidden_units=hidden_units,
    dropout_rate=dropout_rate,
    name="gnn_model",
)

print("GNN output shape:", gnn_model([1, 10, 100]))

print(gnn_model.summary())

modelo = compile_model(gnn_model)

#train_data = ambos_features.iloc[:37943,:]
#test_data = ambos_features.iloc[37943:,:]

train_data = training_features.sample(frac=1)
test_data = validation_features.sample(frac=1)

print("Train data shape:", train_data.shape) 
print("Test data shape:", test_data.shape) 

# Create train and test features as a numpy array.
x_train = train_data[feature_names].to_numpy()
x_test = test_data[feature_names].to_numpy()
# Create train and test targets as a numpy array.
y_train = train_data["label"]
y_test = test_data["label"]


x_train = train_data.node.to_numpy()
print("x_train.dtype = ", x_train.dtype)
print("y_train.dtype = ", y_train.dtype)

#history = run_experiment(modelo, x_train, y_train)

GNN output shape: tf.Tensor(
[[-0.51589584 -0.16580537]
 [ 0.15424332 -0.05034565]
 [ 0.15424332 -0.05034565]], shape=(3, 2), dtype=float32)
Model: "gnn_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 preprocess (Sequential)     (2398933, 32)             1360

 graph_conv1 (GraphConvLayer  multiple                 5888
 )

 graph_conv2 (GraphConvLayer  multiple                 5888
 )

 postprocess (Sequential)    (2398933, 32)             2368

 logits (Dense)              multiple                  66

=================================================================
Total params: 15,570
Trainable params: 14,730
Non-trainable params: 840
_________________________________________________________________
None
Train data shape: (2398933, 6)
Test data shape: (475280, 6)
x_train.dtype =  int64
y_train.dtype =  int64

<ipython-input-8-610d830bb2e9>:26: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  x_train = train_data[feature_names].to_numpy()
<ipython-input-8-610d830bb2e9>:27: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  x_test = test_data[feature_names].to_numpy()

In [13]:
training_features.head()

     node      ID      OD      IDW      ODW  label
0       0       0       1        0     2239      0
1  252661       6       0     2907        0      0
2       1       1       1        6        6      0
3   97219  525631  540374  4796296  4936679      0
4       2       1       1        2        2      0

In [14]:
x_train

array([ 790171,  580089, 2119603, ..., 1217148, 2094851,  583581])

In [15]:
train_data.head()

            node  ID  OD  IDW  ODW  label
2016504   790171   1   0    2    0      0
534827    580089   1   1    1    1      0
1636645  2119603   1   1    1    1      0
411055    443333   1   1    3    3      0
1185943  1710239   1   1    1    1      0

In [16]:
y_train

2016504    0
534827     0
1636645    0
411055     0
1185943    0
          ..
1686292    0
694410     0
663064     0
1513545    0
538007     0
Name: label, Length: 2398933, dtype: int64

In [17]:
history = run_experiment(modelo, x_train, y_train)

Epoch 1/2

ResourceExhaustedError: Graph execution error:

Detected at node 'gnn_model/graph_conv1/sequential/dense_2/MatMul' defined at (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 982, in launch_instance
      app.start()
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelapp.py", line 505, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.8/dist-packages/tornado/platform/asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
      self._run_once()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
      handle._run()
    File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 687, in <lambda>
      lambda f: self._run_callback(functools.partial(callback, future))
    File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 740, in _run_callback
      ret = callback()
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 821, in inner
      self.ctx_run(self.run)
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 782, in run
      yielded = self.gen.send(value)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 365, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 234, in wrapper
      yielded = ctx_run(next, result)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 272, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 234, in wrapper
      yielded = ctx_run(next, result)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 540, in execute_request
      self.do_execute(
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 234, in wrapper
      yielded = ctx_run(next, result)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/ipkernel.py", line 294, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/zmqshell.py", line 536, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2940, in run_cell
      result = self._run_cell(
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2995, in _run_cell
      return runner(coro)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3194, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3373, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3433, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-17-f8ebd21ca8d5>", line 1, in <module>
      history = run_experiment(modelo, x_train, y_train)
    File "<ipython-input-4-8bc1e08016f5>", line 28, in run_experiment
      history = model.fit(
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1409, in fit
      tmp_logs = self.train_function(iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1051, in train_function
      return step_function(self, iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1040, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 889, in train_step
      y_pred = self(x, training=True)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 490, in __call__
      return super().__call__(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "<ipython-input-6-f87cee006bd7>", line 57, in call
      x1 = self.conv1((x, self.edges, self.edge_weights))
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "<ipython-input-5-c947d9aac124>", line 98, in call
      neighbour_messages = self.prepare(neighbour_repesentations, edge_weights)
    File "<ipython-input-5-c947d9aac124>", line 33, in prepare
      messages = self.ffn_prepare(node_repesentations)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 490, in __call__
      return super().__call__(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/sequential.py", line 374, in call
      return super(Sequential, self).call(inputs, training=training, mask=mask)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 458, in call
      return self._run_internal_graph(
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py", line 596, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/layers/core/dense.py", line 221, in call
      outputs = tf.matmul(a=inputs, b=self.kernel)
Node: 'gnn_model/graph_conv1/sequential/dense_2/MatMul'
OOM when allocating tensor with shape[5020771,32] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node gnn_model/graph_conv1/sequential/dense_2/MatMul}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_train_function_7133]

---

# iscx2012 analysis

In [1]:
import os
os.listdir("/root/spektral/datasets/CTU13_original_durRate/")

['graph_20110816_original_durRate.npz',
 'graph_20110816-3_original_durRate.npz',
 'graph_20110811_original_durRate.npz',
 'graph_20110818_original_durRate.npz',
 'graph_20110817_original_durRate.npz',
 'graph_20110819_original_durRate.npz',
 'graph_20110812_original_durRate.npz',
 'graph_20110815-3_original_durRate.npz',
 'graph_20110815-2_original_durRate.npz',
 'graph_20110815_original_durRate.npz',
 'graph_20110810_original_durRate.npz',
 'graph_20110818-2_original_durRate.npz',
 'graph_20110816-2_original_durRate.npz']

In [1]:
from spektral.data import DisjointLoader, BatchLoader, Dataset, Graph
import numpy as np

class CTU13_original_durRate(Dataset):
    
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def download(self):
        os.mkdir(self.path)
        
        captures = ["10","11","12","15","15-2","16","16-2","16-3","17","18","18-2","19","15-3"]
        
        # para poder descargar los archivos ncol de cada captura y las features de cada nodo

        features_links = ["ktAgJS22kBXcMsT", 
                          "qfM8pjZgDi9EFfd",
                          "34PWCn9JmdDA9HE",
                          "YtcCmiNEyPiYB4Y",
                          "D2HdaEZYcFz5ryt",
                          "cTY262moFLGjtmn",
                          "TbfPFbSKWqYqR7n",
                          "s2GTjFz8rNxbs4z",
                          "9dZPAENNACreDEK",
                          "bwR2Zrky49JjtgA",
                          "CmYc9JyBsHwzaYD",
                          "TNSkGJcq2CPoFtM",
                          "XwZFrQYzMLNJxAY"
        ]
        
        
        dur_rate = ["nFprrYtrZsW8Fwj",
                    "WEzZ9CYcFHPkYWk",
                    "wJHqrAgwbQLrFz3",
                    "fY7KkRzr6Re9BWP",
                    "4CHHTiYWqXCs9Ln",
                    "4orMAcGx9xitKLa",
                    "Jb9Qm35tG2QagkC",
                    "ikjFiFaMLWr8scL",
                    "Y2aSjmCxKxQ6oWZ",
                    "YZFQpTTL7cxLNgY",
                    "Z34rnW6YXMSLZKm",
                    "qA4KZ25WC4BwZKn",
                    "6ZiXnr99jLxE2oC"
        ]

        
        ncol_links = ["B5EBDnAr4z55cc9",
                      "Pz4ba4jn3nCNgAp",
                      "EbkwSBHyAkHmdHE",
                      "ttyoxLc36s7ABCB",
                      "R3b9fe25x6ncoaT",
                      "wFZ72f9kL3XFki6",
                      "7EcYp9ACPqkQqDs",
                      "YcTZCARwKCY2jiB",
                      "3cc8mcTZaEC9LGM",
                      "NDgw4PwXAwQKgb2",
                      "wY38ypkj7QSJYib",
                      "dEZYJ84z53ozZZo",
                      "NKdZfBX6DG9nB8o"            
        ]
        
        for i in range(len(captures)):
            # x = nodes features (Dur, Rate)
            # a = adjacency matrix
            # y =labels
            
            # Read files with nodes features (csv file) and connections between nodes (ncol file)
            x_4label = pd.read_csv(f'https://nube.ingenieria.uncuyo.edu.ar/s/{features_links[i]}/download', sep=",", header=0)
            x_4label = x_4label.sort_values("node")
            
            x_tmp = pd.read_csv(f'https://nube.ingenieria.uncuyo.edu.ar/s/{dur_rate[i]}/download', sep=",", header=0)
    
            a_tmp = pd.read_csv(f'https://nube.ingenieria.uncuyo.edu.ar/s/{ncol_links[i]}/download', sep=" ", header=None, names=["source", "target", "weight"])
            
            
            # Create dictionaries that identify each node and label with an integer
            node_idx = {name: idx for idx, name in enumerate(sorted(x_4label["node"].unique()))}
            
            # Change node names and label for their corresponding integer
            a_tmp["source"] = a_tmp["source"].apply(lambda name: node_idx[name])
            a_tmp["target"] = a_tmp["target"].apply(lambda name: node_idx[name])
            
            # Node features: (Dur, Rate)
            x = x_tmp.sort_values("node")[x_tmp.columns.difference(["node"], sort=False)].to_numpy()       
            x = x.astype(np.float32)
            
            # Separate source, target and weight to create a sparce matrix
            a_source = a_tmp[["source"]].to_numpy().T
            a_source = np.reshape(a_source, a_source.shape[-1])
            a_target = a_tmp[["target"]].to_numpy().T
            a_target = np.reshape(a_target, a_target.shape[-1])
            a_weight = a_tmp[["weight"]].to_numpy().T
            a_weight = np.reshape(a_weight, a_weight.shape[-1])
            # Adjacency matrix:
            a = sparse.csr_matrix((a_weight, (a_source, a_target)), shape=(x.shape[0], x.shape[0]), dtype=np.float32)
            
            # Label (CTU13 original):
            class_idx = {'normal': 0, 'infected':1}
            x_4label["label"] = x_4label["label"].apply(lambda value: class_idx[value])
            
            y = x_4label.sort_values("node")["label"].to_numpy()
            y = y.astype(np.float32)
            y = _normalize(y[:, None], "ohe") #one-hot encoding

                
            # Save in format npz
            filename = os.path.join(self.path, f'graph_201108{captures[i]}_original_durRate.npz')
            np.savez(filename, x=x, a=a, y=y)

            # Free memory
            del x_4label, x_tmp, x, a_tmp, a_source, a_target, a_weight, a, y
            gc.collect()


    def read(self):
        # We must return a list of Graph objects
        output = []
        
        captures = ["10","11","12","15","15-2","16","16-2","16-3","17","18","18-2","19","15-3"]

        for i in captures:
            data = np.load(os.path.join(self.path, f'graph_201108{i}_original_durRate.npz'), allow_pickle=True)
            output.append(
                Graph(x=data['x'], a=data['a'][()], y=data['y']) # también puede ser a=data['a'].item()
            )

        return output

In [8]:
datos = CTU13_original_durRate()

In [11]:
datos[0].x

array([[3.1280095e+03, 1.0200886e-01],
       [6.4778000e+01, 1.6981100e-01],
       [1.0804866e+01, 2.7765301e-01],
       ...,
       [1.0087467e-01, 9.9133053e+00],
       [1.0092783e-01, 9.9081430e+00],
       [1.0111883e-01, 9.8948593e+00]], dtype=float32)

In [13]:
os.listdir("/mnt")

['ctu13', 'NetSecGame-copy', 'synthetic', '__pycache__', 'NetSecGame', 'fides']

In [2]:
import pandas as pd

In [2]:
df = pd.read_csv("/mnt/iscx2012/iscx2012.11.143.csv")
df.columns = df.columns.str.strip()

In [71]:
df_subset=df.iloc[:,[2,3,12,13,14,15,16,17,18,19,20,21,22,23,24,25,28]].copy()
df_subset.columns

Index(['sport', 'dport', 'flowprotocol', 'flowconntime', 'numpackets',
       'numbytes', 'bps', 'bpp', 'load', 'rate', 'aggsip', 'aggdip',
       'aggdipsport', 'aggsipdport', 'aggdipsamedport', 'aggnumberofflows',
       'snortclasses'],
      dtype='object')

In [77]:
src2dst = df_subset[["sport", "dport", 'flowprotocol', 'flowconntime', 'numpackets',
       'numbytes', 'bps', 'bpp', 'load', 'rate', 'aggsip', 'aggdip',
       'aggdipsport', 'aggsipdport', 'aggdipsamedport', 'aggnumberofflows',
       'snortclasses']].copy()
dst2src = df_subset[["dport", "sport", 'flowprotocol', 'flowconntime', 'numpackets',
       'numbytes', 'bps', 'bpp', 'load', 'rate', 'aggsip', 'aggdip',
       'aggdipsport', 'aggsipdport', 'aggdipsamedport', 'aggnumberofflows',
       'snortclasses']].copy()

src2dst.rename(columns={'sport': 'origin', 'dport': 'destination', 'numbytes': 'weight'}, inplace=True)
dst2src.rename(columns={'dport': 'origin', 'sport': 'destination', 'numbytes': 'weight'}, inplace=True)

concatAll = pd.concat([src2dst, dst2src], ignore_index=True)
finalDF = concatAll.groupby(['origin','destination'], as_index=False).mean().copy()
finalDF

,origin,destination,flowprotocol,flowconntime,numpackets,weight,bps,bpp,load,rate,aggsip,aggdip,aggdipsport,aggsipdport,aggdipsamedport,aggnumberofflows,snortclasses
0,0,0,2.0,0.000000,1.0,105.75,0.000000,105.750000,0.000000e+00,0.000000,5.0,4.0,2.0,1.0,4.0,13.0,1.0
1,22,4133,0.0,5.447715,72.0,10252.00,1881.889930,142.388889,1.484366e+04,13.032988,2.0,1.0,2.0,1.0,1.0,4.0,0.0
2,22,4134,0.0,1.799327,31.0,5530.00,3073.371322,178.387097,2.376889e+04,16.672900,1.0,9.0,1.0,3.0,1.0,53.0,0.0
3,22,4135,0.0,5.444115,73.0,10312.00,1894.155432,141.260274,1.494311e+04,13.225290,1.0,3.0,1.0,3.0,1.0,16.0,0.0
4,22,4136,0.0,5.315659,76.0,17504.00,3292.912506,230.315789,2.599264e+04,14.109257,2.0,2.0,1.0,1.0,2.0,13.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2629,64144,53,1.0,0.001131,3.0,446.00,394341.290893,148.666667,1.577365e+06,1768.346600,5.0,9.0,2.0,1.0,9.0,44.0,0.0
2630,65032,53,1.0,0.253372,2.0,230.00,907.756185,115.000000,0.000000e+00,3.946766,12.0,12.0,1.0,1.0,12.0,35.0,1.0
2631,65114,53,1.0,0.011820,2.0,244.00,20642.978003,122.000000,0.000000e+00,84.602371,6.0,5.0,2.0,1.0,5.0,12.0,1.0
2632,65250,53,1.0,0.011206,2.0,564.00,50330.180261,282.000000,0.000000e+00,89.237907,32.0,32.0,1.0,1.0,32.0,70.0,1.0
2633,65505,53,1.0,0.085505,2.0,226.00,2643.120285,113.000000,0.000000e+00,11.695222,13.0,13.0,1.0,1.0,13.0,48.0,1.0

In [88]:
labels = finalDF[["origin","snortclasses"]].groupby(['origin'], as_index=False).mean()
labels["snortclasses"] = labels["snortclasses"].apply(lambda x: 0 if x < 0.5 else 1)
labels

      origin  snortclasses
0          0             1
1         22             0
2         25             0
3         53             1
4         80             0
...      ...           ...
1304   64144             0
1305   65032             1
1306   65114             1
1307   65250             1
1308   65505             1

[1309 rows x 2 columns]

In [90]:
adj_aux = finalDF[["origin","destination","weight"]]
adj_aux

      origin  destination    weight
0          0            0    105.75
1         22         4133  10252.00
2         22         4134   5530.00
3         22         4135  10312.00
4         22         4136  17504.00
...      ...          ...       ...
2629   64144           53    446.00
2630   65032           53    230.00
2631   65114           53    244.00
2632   65250           53    564.00
2633   65505           53    226.00

[2634 rows x 3 columns]

In [91]:
x_aux = finalDF[["origin",'flowprotocol', 'flowconntime', 'numpackets',
                    'bps', 'bpp', 'load', 'rate', 'aggsip', 'aggdip',
       'aggdipsport', 'aggsipdport', 'aggdipsamedport', 'aggnumberofflows']].groupby(['origin'], as_index=False).mean()
x_aux

,origin,flowprotocol,flowconntime,numpackets,bps,bpp,load,rate,aggsip,aggdip,aggdipsport,aggsipdport,aggdipsamedport,aggnumberofflows
0,0,2.0,0.000000,1.000000,0.000000,105.750000,0.000000e+00,0.000000,5.000000,4.000000,2.000000,1.000000,4.000000,13.000000
1,22,0.0,4.840568,163.333333,21884.087157,263.284133,1.742701e+05,35.812406,2.000000,3.200000,1.400000,1.800000,1.533333,17.400000
2,25,0.0,0.169958,12.000000,5510.583923,76.666667,4.010747e+04,65.887415,6.400000,1.000000,2.000000,1.000000,1.000000,11.400000
3,53,1.0,0.319356,2.058837,26727.135774,188.858504,5.254793e+04,76.066976,9.158995,8.065883,1.194046,1.069408,7.948232,28.610217
4,80,0.0,19.870398,50.626709,14154.455425,383.143202,1.042202e+05,42.332722,13.319664,11.711356,1.282860,1.018402,11.676656,23.807045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,64144,1.0,0.001131,3.000000,394341.290893,148.666667,1.577365e+06,1768.346600,5.000000,9.000000,2.000000,1.000000,9.000000,44.000000
1305,65032,1.0,0.253372,2.000000,907.756185,115.000000,0.000000e+00,3.946766,12.000000,12.000000,1.000000,1.000000,12.000000,35.000000
1306,65114,1.0,0.011820,2.000000,20642.978003,122.000000,0.000000e+00,84.602371,6.000000,5.000000,2.000000,1.000000,5.000000,12.000000
1307,65250,1.0,0.011206,2.000000,50330.180261,282.000000,0.000000e+00,89.237907,32.000000,32.000000,1.000000,1.000000,32.000000,70.000000
1308,65505,1.0,0.085505,2.000000,2643.120285,113.000000,0.000000e+00,11.695222,13.000000,13.000000,1.000000,1.000000,13.000000,48.000000

In [99]:
from scipy import sparse
a_source = adj_aux[["origin"]].to_numpy().T
a_source = np.reshape(a_source, a_source.shape[-1])
a_target = adj_aux[["destination"]].to_numpy().T
a_target = np.reshape(a_target, a_target.shape[-1])
a_weight = adj_aux[["weight"]].to_numpy().T
a_weight = np.reshape(a_weight, a_weight.shape[-1])
#a = sparse.csr_matrix((a_weight, (a_source, a_target)), shape=(x_aux.shape[0], x_aux.shape[0]), dtype=np.float32)
a_source

array([    0,    22,    22, ..., 65114, 65250, 65505])

In [67]:
set(df_subset["dport"])

{0,
 22,
 25,
 53,
 80,
 110,
 137,
 138,
 139,
 143,
 443,
 1090,
 1112,
 1452,
 1863,
 2354,
 2630,
 2631,
 2756,
 5353,
 50849}

In [66]:
80 in set(df_subset1["sport"])

False

In [59]:
50849 in set(df_subset1["sport"]) #22,25,53,110,139,443,1452,1863,2630,2631,2756,50849

False

In [70]:
df_subset.loc[df_subset["dport"]==22]

,sport,dport,flowprotocol,flowconntime,numpackets,numbytes,bps,bpp,load,rate,aggsip,aggdip,aggdipsport,aggsipdport,aggdipsamedport,aggnumberofflows,snortclasses,node
1001,4133,22,0,5.447715,72,10252,1881.889930,142.388889,1.484366e+04,13.032988,2,1,2,1,1,4,0,"(4133, 22)"
1054,4134,22,0,1.799327,31,5530,3073.371322,178.387097,2.376889e+04,16.672900,1,9,1,3,1,53,0,"(4134, 22)"
1279,4135,22,0,5.444115,73,10312,1894.155432,141.260274,1.494311e+04,13.225290,1,3,1,3,1,16,0,"(22, 4135)"
1291,4136,22,0,5.315659,76,17504,3292.912506,230.315789,2.599264e+04,14.109257,2,2,1,1,2,13,0,"(4136, 22)"
1306,4137,22,0,5.372204,73,15752,2932.129904,215.780822,2.313241e+04,13.402321,1,1,1,1,1,13,0,"(4137, 22)"
1322,4139,22,0,5.307108,70,10976,2068.169707,156.800000,1.630568e+04,13.001431,4,4,3,2,2,17,1,"(4139, 22)"
1336,4141,22,0,5.308474,67,9558,1800.517437,142.656716,1.418713e+04,12.432951,5,4,3,2,2,20,0,"(4141, 22)"
1352,4142,22,0,5.339936,57,7910,1481.291162,138.771930,1.163909e+04,10.487018,1,2,1,2,1,14,0,"(4142, 22)"
1363,4143,22,0,5.376897,88,33348,6202.090165,378.954545,4.904688e+04,16.180336,2,3,1,2,2,12,0,"(22, 4143)"
1384,4144,22,0,5.348510,56,7850,1467.698481,140.178571,1.152919e+04,10.283238,2,5,1,3,2,23,0,"(4144, 22)"
1401,4145,22,0,5.365249,70,9968,1857.882085,142.400000,1.464834e+04,12.860540,1,1,1,1,1,13,1,"(4145, 22)"
1419,4146,22,0,5.335985,57,7974,1494.382012,139.894737,1.174216e+04,10.494782,2,5,1,2,2,19,0,"(4146, 22)"
1435,4147,22,0,6.222860,1522,1656148,266139.363572,1088.139290,2.127716e+06,244.421381,3,5,2,2,2,19,1,"(4147, 22)"
1452,4148,22,0,5.375933,108,57348,10667.543662,531.000000,8.454420e+04,19.903521,1,1,1,1,1,11,0,"(4148, 22)"
1465,4149,22,0,0.248547,30,5470,22007.909973,182.333333,1.700121e+05,116.678132,2,2,1,1,2,14,0,"(4149, 22)"

In [63]:
df_subset1=df_subset[df_subset['dport'].isin(set(df_subset["sport"]))]
df_subset1

,sport,dport,flowprotocol,flowconntime,numpackets,numbytes,bps,bpp,load,rate,aggsip,aggdip,aggdipsport,aggsipdport,aggdipsamedport,aggnumberofflows,snortclasses,node
0,50850,80,0,0.240693,12,4107,17063.229924,342.250000,124108.304688,45.701370,0,0,0,0,0,0,0,"(80, 50850)"
1,50851,80,0,52.825218,36,8802,166.624963,244.500000,1294.987549,0.662562,1,1,1,1,1,1,1,"(80, 50851)"
2,143,1090,0,480.036530,15,1010,2.104007,67.333333,15.632144,0.029164,1,1,1,1,1,2,0,"(1090, 143)"
3,50852,80,0,0.255126,11,3425,13424.739149,311.363636,96673.796875,39.196319,2,1,1,1,1,3,0,"(80, 50852)"
4,2497,80,0,14.436906,2,120,8.312030,60.000000,0.000000,0.069267,1,1,1,1,1,4,0,"(80, 2497)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1466,4391,80,0,0.719910,12,4645,6452.195413,387.083333,46928.085938,15.279687,11,11,1,1,11,15,0,"(80, 4391)"
1467,4392,80,0,0.721692,15,7003,9703.585463,466.866667,72086.148438,19.398856,12,12,1,1,12,16,0,"(4392, 80)"
1468,4393,80,0,0.717314,14,6017,8388.237229,429.785714,61953.343750,18.123165,11,11,1,1,11,14,0,"(80, 4393)"
1469,4394,80,0,0.713231,12,4919,6896.783791,409.916667,50160.464844,15.422773,12,12,1,1,12,15,0,"(80, 4394)"
1470,4395,80,0,0.232076,4,362,1559.833848,90.500000,8342.094727,12.926800,11,11,1,1,11,14,0,"(80, 4395)"

In [15]:
set(df_subset["sport"])-set(df_subset["dport"])

{24425,
 32780,
 4127,
 4132,
 4133,
 4134,
 4135,
 4136,
 4137,
 4138,
 4139,
 4140,
 4141,
 4142,
 4143,
 4144,
 4145,
 4146,
 4147,
 4148,
 4149,
 53307,
 57414,
 4170,
 4178,
 4179,
 4180,
 4181,
 4182,
 4183,
 4184,
 4185,
 4186,
 4187,
 61532,
 4188,
 4189,
 4190,
 16480,
 4191,
 4192,
 4193,
 4194,
 4195,
 4196,
 4197,
 4198,
 4199,
 4200,
 4201,
 4202,
 4204,
 4205,
 4206,
 4207,
 4203,
 4209,
 4210,
 4208,
 4212,
 4211,
 4214,
 4213,
 4216,
 4217,
 4215,
 32892,
 4219,
 4218,
 4220,
 4222,
 4221,
 4223,
 4224,
 4225,
 4226,
 4227,
 36997,
 4229,
 4228,
 4232,
 4230,
 4231,
 4235,
 4236,
 4237,
 24723,
 4238,
 4240,
 4241,
 4242,
 4239,
 4245,
 4246,
 4247,
 41116,
 4248,
 4250,
 4251,
 4252,
 4253,
 4249,
 4254,
 4256,
 4255,
 4258,
 4257,
 4260,
 4261,
 4262,
 4263,
 4259,
 4264,
 4266,
 4267,
 4268,
 4265,
 41138,
 4270,
 4269,
 4271,
 53425,
 4272,
 4273,
 4276,
 4277,
 4278,
 41148,
 4280,
 4281,
 4282,
 4283,
 4284,
 4287,
 4288,
 4285,
 4290,
 4291,
 4292,
 53445,
 4293,
 28871,
 4296,
 4297,
 4298,
 4294,
 4300,
 4301,
 4302,
 4303,
 4304,
 4305,
 4306,
 4307,
 4308,
 4309,
 4310,
 4311,
 4312,
 4313,
 4314,
 4315,
 4316,
 4317,
 4318,
 4319,
 4320,
 4321,
 4322,
 4323,
 4324,
 4325,
 4326,
 4327,
 4328,
 4329,
 4330,
 4331,
 4332,
 4333,
 4334,
 4335,
 4336,
 4337,
 4338,
 4339,
 4340,
 4341,
 4342,
 61687,
 4343,
 4344,
 4345,
 4346,
 4347,
 4348,
 4349,
 4350,
 4351,
 4352,
 4353,
 4355,
 4356,
 4354,
 4358,
 4357,
 4360,
 4359,
 4361,
 4363,
 4364,
 4365,
 4366,
 4367,
 4368,
 4369,
 4370,
 4371,
 4372,
 4373,
 4374,
 4375,
 4376,
 4377,
 4378,
 4379,
 4380,
 4381,
 61726,
 4382,
 4383,
 4384,
 4385,
 4386,
 4387,
 4388,
 4390,
 4391,
 4392,
 4389,
 4393,
 4394,
 4396,
 53549,
 4397,
 4395,
 4398,
 4399,
 4400,
 4401,
 4402,
 4403,
 4404,
 4405,
 4408,
 4409,
 4410,
 20795,
 4411,
 4413,
 4414,
 4415,
 4416,
 4417,
 4418,
 4419,
 4420,
 4421,
 4422,
 57674,
 4423,
 4424,
 4425,
 4426,
 4427,
 4428,
 4429,
 4430,
 4431,
 33108,
 4432,
 4433,
 4434,
 4435,
 4436,
 4437,
 4438,
 4439,
 4440,
 24926,
 4441,
 4442,
 33121,
 4443,
 4444,
 4445,
 16741,
 4446,
 4447,
 4448,
 4449,
 4450,
 4451,
 4452,
 4453,
 4454,
 4455,
 4456,
 4457,
 4458,
 4459,
 4460,
 4461,
 4462,
 4463,
 4464,
 16761,
 16762,
 4466,
 4467,
 4468,
 4469,
 4470,
 4471,
 4472,
 24970,
 20874,
 8593,
 4412,
 45472,
 33197,
 57775,
 57074,
 29109,
 12737,
 53710,
 61904,
 8662,
 49630,
 20967,
 57832,
 25109,
 61980,
 57893,
 21033,
 33327,
 57907,
 25140,
 16952,
 21082,
 53854,
 65250,
 37510,
 58063,
 29393,
 41682,
 4871,
 4872,
 4873,
 4874,
 49931,
 4875,
 8973,
 49946,
 13086,
 4233,
 4234,
 45911,
 13153,
 4243,
 37734,
 4244,
 17280,
 9102,
 25558,
 62427,
 9180,
 13281,
 25574,
 4274,
 1027,
 4275,
 1041,
 4279,
 33833,
 1069,
 1071,
 1072,
 1074,
 1075,
 1076,
 1077,
 42038,
 1078,
 1079,
 1080,
 1081,
 1082,
 1083,
 1084,
 1085,
 1086,
 1087,
 1088,
 1089,
 1091,
 1093,
 1094,
 1092,
 1096,
 1095,
 1097,
 1098,
 1099,
 1100,
 1101,
 1102,
 1103,
 1104,
 1105,
 1106,
 1107,
 1108,
 1109,
 1110,
 1111,
 1113,
 1114,
 1115,
 1116,
 1117,
 1118,
 1119,
 1120,
 1121,
 1122,
 1123,
 1124,
 1125,
 1126,
 1127,
 1128,
 1129,
 1130,
 1131,
 1132,
 1133,
 1134,
 1135,
 1136,
 1137,
 1138,
 1139,
 1140,
 1141,
 1142,
 1143,
 50297,
 1144,
 1145,
 1146,
 1147,
 1148,
 1149,
 1150,
 1151,
 1152,
 1153,
 17540,
 1154,
 1155,
 1156,
 1157,
 1158,
 1159,
 1160,
 1161,
 1162,
 1163,
 1164,
 1165,
 1166,
 1167,
 1168,
 1169,
 1170,
 1171,
 1172,
 1173,
 1174,
 1175,
 1176,
 1177,
 1178,
 1179,
 1180,
 1181,
 1182,
 1183,
 1184,
 1185,
 1186,
 1187,
 1188,
 1189,
 1190,
 1191,
 1192,
 1193,
 1194,
 1195,
 1196,
 1197,
 1198,
 1199,
 42163,
 1200,
 1201,
 1202,
 1203,
 1204,
 58560,
 46286,
 1252,
 46310,
 9450,
 42218,
 30373,
 58638,
 50463,
 38177,
 4286,
 9535,
 34113,
 42307,
 30035,
 50518,
 58735,
 62835,
 34173,
 4289,
 9615,
 26012,
 13724,
 42404,
 58798,
 30130,
 4362,
 46524,
 38338,
 26053,
 50644,
 34263,
 42460,
 5602,
 30178,
 62951,
 62953,
 1517,
 30217,
 4295,
 42535,
 5697,
 22087,
 13909,
 50788,
 1638,
 13944,
 4299,
 1660,
 1673,
 1674,
 1675,
 1676,
 50833,
 4406,
 4407,
 50846,
 50850,
 50851,
 50852,
 50853,
 50854,
 50855,
 50856,
 50857,
 50858,
 50859,
 50860,
 50861,
 50862,
 50863,
 50864,
 50865,
 50866,
 50867,
 50868,
 50869,
 50870,
 50871,
 50872,
 50873,
 50874,
 50875,
 50876,
 50877,
 50878,
 50879,
 50880,
 50881,
 50882,
 50883,
 50884,
 50885,
 50886,
 50887,
 50888,
 50889,
 50890,
 50891,
 50892,
 50893,
 50894,
 50895,
 50896,
 50897,
 50898,
 50899,
 50900,
 50901,
 50902,
 50903,
 50904,
 50905,
 50906,
 50907,
 50908,
 50909,
 50910,
 50911,
 50912,
 50913,
 50914,
 50915,
 50916,
 50917,
 50918,
 50919,
 50920,
 50921,
 50922,
 50923,
 50924,
 50925,
 50926,
 50927,
 50928,
 50929,
 50930,
 50931,
 50932,
 50933,
 50934,
 50935,
 50936,
 50937,
 50938,
 50939,
 50940,
 50941,
 50942,
 50943,
 50944,
 50945,
 50946,
 50947,
 50948,
 50949,
 50950,
 50951,
 50952,
 50953,
 50954,
 50955,
 50956,
 50957,
 50958,
 50959,
 50960,
 50961,
 50962,
 50963,
 50964,
 50965,
 50966,
 50967,
 50968,
 50969,
 50970,
 50971,
 50972,
 50973,
 50974,
 50975,
 50976,
 50977,
 46875,
 1830,
 18223,
 18224,
 55096,
 55097,
 30527,
 31305,
 30542,
 51038,
 63394,
 55203,
 63400,
 30648,
 4465,
 59340,
 30670,
 59358,
 54947,
 22504,
 38891,
 55276,
 30701,
 10227,
 34806,
 63510,
 59428,
 2109,
 43070,
 10331,
 2146,
 34925,
 2176,
 51336,
 47240,
 55437,
 51384,
 47290,
 35030,
 55531,
 39159,
 2339,
 2340,
 2341,
 2342,
 2343,
 2344,
 2345,
 2346,
 2347,
 2348,
 2349,
 2350,
 2351,
 2352,
 2353,
 2355,
 2356,
 2357,
 2358,
 2359,
 2360,
 2361,
 2362,
 2386,
 39265,
 59094,
 14695,
 35196,
 29793,
 39313,
 2451,
 2452,
 2453,
 2454,
 2455,
 2456,
 2457,
 2458,
 27029,
 51610,
 2459,
 2460,
 2461,
 2462,
 2463,
 2464,
 2465,
 2466,
 2467,
 2468,
 59823,
 39354,
 2497,
 2503,
 2505,
 2507,
 2510,
 31185,
 2516,
 2521,
 2524,
 2525,
 2526,
 2527,
 47580,
 40642,
 47617,
 43523,
 51723,
 3769,
 2589,
 27166,
 29010,
 51756,
 18994,
 2620,
 2622,
 2623,
 39489,
 19014,
 64071,
 2632,
 2633,
 2634,
 2635,
 2636,
 2637,
 2638,
 2639,
 2640,
 2641,
 2642,
 2643,
 2644,
 2645,
 2646,
 2647,
 2648,
 2649,
 2650,
 19040,
 51822,
 39534,
 60027,
 64144,
 6811,
 35507,
 47822,
 19160,
 10981,
 2795,
 10988,
 19185,
 39668,
 43777,
 35590,
 60178,
 39705,
 2850,
 6965,
 23356,
 39756,
 6999,
 56151,
 43875,
 3838,
 23416,
 7047,
 11148,
 48013,
 2962,
 2964,
 2965,
 2966,
 2971,
 60332,
 60334,
 19379,
 7923,
 11193,
 19386,
 3853,
 3009,
 31699,
 3030,
 3034,
 7133,
 7142,
 39942,
 48143,
 31760,
 39959,
 7201,
 27707,
 7229,
 52299,
 60513,
 7268,
 31845,
 44159,
 45413,
 27783,
 7338,
 44204,
 11451,
 52432,
 23762,
 36057,
 3298,
 3339,
 56605,
 24285,
 23885,
 52579,
 15720,
 11627,
 3441,
 40307,
 15732,
 36233,
 15768,
 15769,
 15770,
 15771,
 56732,
 40348,
 15775,
 15776,
 15777,
 15778,
 15779,
 15780,
 15781,
 15782,
 15783,
 15784,
 15785,
 15786,
 15787,
 15788,
 15789,
 36283,
 15844,
 28140,
 65032,
 11789,
 3972,
 3973,
 56860,
 3975,
 32291,
 3976,
 56890,
 60987,
 52813,
 65114,
 28252,
 44636,
 48759,
 11936,
 3749,
 28326,
 3750,
 3751,
 3752,
 3753,
 3754,
 3755,
 3756,
 3757,
 3758,
 3759,
 3760,
 3761,
 3762,
 3763,
 3764,
 3765,
 20142,
 3766,
 3767,
 3768,
 3770,
 3771,
 3772,
 3773,
 3774,
 3775,
 3776,
 3777,
 3778,
 3779,
 3780,
 ...}

In [5]:
# Unir sport y dport en una sola columna de nodos
df_subset['node'] = df_subset[['sport', 'dport']].apply(lambda x: frozenset(x), axis=1)

# Seleccionar las columnas de características
feature_columns = df_subset.columns.difference(['sport', 'dport', 'node', 'snortclasses'])

# Calcular el promedio de las características para cada nodo
node_features = df_subset.groupby('node')[feature_columns].mean().reset_index()

# Mostrar el DataFrame de características de los nodos
node_features

,node,aggdip,aggdipsamedport,aggdipsport,aggnumberofflows,aggsip,aggsipdport,bpp,bps,flowconntime,flowprotocol,load,numbytes,numpackets,rate
0,"(80, 50850)",0.0,0.0,0.0,0.0,0.0,0.0,342.250000,17063.229924,0.240693,0.0,124108.304688,4107.0,12.0,45.701370
1,"(11936, 53)",1.0,1.0,1.0,8.0,3.0,1.0,75.000000,8.514395,17.617224,1.0,0.000000,150.0,2.0,0.056763
2,"(80, 50946)",1.0,1.0,1.0,10.0,1.0,1.0,129.272727,108.093094,13.155327,0.0,778.391907,1422.0,11.0,0.760148
3,"(53, 24285)",2.0,2.0,1.0,10.0,5.0,1.0,75.000000,0.000000,0.000000,1.0,0.000000,75.0,1.0,0.000000
4,"(80, 1189)",2.0,2.0,1.0,9.0,2.0,1.0,124.800000,1828.057162,0.682692,0.0,13007.330078,1248.0,10.0,13.183105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1314,"(80, 1123)",5.0,5.0,1.0,6.0,5.0,1.0,814.672566,23853.752539,3.859267,0.0,189128.140625,92058.0,113.0,29.021055
1315,"(80, 1122)",4.0,4.0,1.0,5.0,4.0,1.0,815.631579,7373.479663,10.508607,0.0,58360.542969,77485.0,95.0,8.945049
1316,"(80, 1121)",3.0,3.0,1.0,4.0,3.0,1.0,124.800000,1762.241436,0.708189,0.0,12539.025391,1248.0,10.0,12.708472
1317,"(80, 1119)",2.0,2.0,1.0,5.0,2.0,1.0,124.800000,1836.268960,0.679639,0.0,13065.760742,1248.0,10.0,13.242325
1318,"(4149, 22)",2.0,2.0,1.0,14.0,2.0,1.0,182.333333,22007.909973,0.248547,0.0,170012.109375,5470.0,30.0,116.678132

In [32]:
concatAll

      origin  destination  weight
0      50850           80    4107
1      50851           80    8802
2        143         1090    1010
3      50852           80    3425
4       2497           80     120
...      ...          ...     ...
2937      80         4391    4645
2938      80         4392    7003
2939      80         4393    6017
2940      80         4394    4919
2941      80         4395     362

[2942 rows x 3 columns]